src/raygui.h

- Added static bool dropOpen to track if the dropdown is currently open.
- Fixes bug where dropdown would change when closed if a element that overlaps is pressed.

Only run dropdown collision check if dropdown open

---

src/raygui.h

Reset dropOpen when dropdown closed. Forgot to add in previous commit

Fix dropOpen reset and added dllexport

---

.gitignore
src/raygui.h

I was encountering a crash when editing a textbox by adding more characters than the char[] could handle. While attempting this from the end of the textbox it would simply not enter the characters, adding the new characters from a position before the end of the array causes the error.
This is the fix I've implemented.

Fixed crash when editing textbox at non-end pos

---

src/raygui.h

Fixes bug in GuiTextBox if you type and the text buffer has non-zero data after the null terminator (which it might have!). Now adding a null terminator after the typed text.

fix textbox bug

---

src/raygui.h

I am using raygui with my own engine not raylib and these changes are to make it easier to update to the latest version of raygui.
I am implementing the required functions in my own source code file so that I can update raygui by simply copying over the latest raygui.h file and not have to make the same changes to the file each time.
To allow this there should not be 'dummy' implementations of the required functions in raygui itself.

standalone integration improvements

---

src/raygui.h

I encountered a lot of errors and warning when using raygui in my C++ project. 
I modified raygui.h to make it both C and C++ compliant.
The most significant changes that I made are:
1. For curly intialisations I created a macro named `CURLY_INIT` which expands to `StructName { }` in C++ and `(StructName) { }` in C.
2. I had to add a lot of casts to float because in C++ I would get the error "Conversion from 'int' to 'float' requires a narrowing conversion".
I tested by compiling an example in C and one in C++ using the MSVC compiler, but I didn't add my testing setup to the project since I didn't want to mess with it that much.
In my testing setup I also didn't set the warning level manually, I just left it on the default, so there might be more warnings when compiling for C++ on higher …

Patched raygui to make it both C and C++ compliant

---

README.md
src/raygui.h

The guigrid don't deal with the parameter subdivs correctly.
I just found out that the multiline textbox in "raygui.h" not work well because of 'index out of bounds'. The lastLine would always be NULL, so that it would cause access to index -1 of the lastLine .

:bug: Fixed GuiGrid, GuiTextBoxMult, README (outdated #define for icons)

---

examples/custom_file_dialog/gui_file_dialog.h

Compiler expected a static value. Writing 64 directly in the declaration should fix it up.

Fix unknown stack array size

---

README.md

Added a missing parenthesis to the if statement for the *iconId* example.

Missing closing parentheses for `if` statement

---

src/raygui.h

If you have a style file with CRLF line endings and specify a font file on a system that expects LF line endings, then the font file will fail to load with an error such as...
```
WARNING: FILEIO: [./assets/terminal/Mecha.ttf
] Failed to open file
```
...because it sees the CR as part of the name.
Adding '\r' to the negated scanset for sscanf() fixes the issue.

Handle CRLF line endings reading fontFileName.

---

src/raygui.h

The current raygui code does not correctly define RAYGUIDEF for windows DLLs with correct 'C' externs.
This PR changes the RAYGUIDEF over to work like the one in raylib so it works on windows.

Fix dll import/export and extern to work like raylib

---

examples/scroll_panel/gui_scroll_panel.c

Scroll_panel example (https://github.com/raysan5/raygui/tree/master/examples/scroll_panel) uses two slide bars that should allow change of content area dimensions, but they were stuck and either set to the maximum value, or 1 while clicked (see the gif1).
Correcting arguments taken by `GuiSliderBar()` functions that correspond to `panelContentRec` dimensions fixed the bug and now slide bars work as intended (see gif2):.
It's kinda weird tho how there was `bool` argument in the `GuiSliderBar()` functions which definition doesn't use any argument of that type - was an older version of this function using `bool` type argument and it was left there causing a bug?

Fixed bug with stuck slide bars in scroll_panel example

---

src/raygui.h

This PR fixes all the typecast warnings for int to float, float to int, and size_t to int. This should prevent systems that treat these warnings as errors from working.
It was tested by running the controls_test_suite with the changes and everything seemed to look good.

Fix typecast warnings

---

src/raygui.h

1. fixed the bug of the scroll bars disappearing
2. implemented scroll bar side checking for drawing the little rectangle in the corner of the two scrollbars
The problem was that the scroll panel width was set to 0
This happened because the way the width was calculated was as follows (simplified):
```cpp
float panelWidth = ...;
float contentWidth = ...;
int scrollBarWidth = (int)(panelWidth / (int)content.height) * (int)panelWidth;
```
This first calculates the ratio between content and panel and then multiplies that by the panelWidth
Now the problem with that is that the ratio will allways be <0 (because content.height>panelWidth) which means when this ratio is converted to an int it will always be 0 => the slide bar width will be 0
To fix this I simply didnt cast the ratio to an int but …

Scroll panel fix

---

src/raygui.h

Related https://github.com/raysan5/raygui/pull/121
It is moved above to be same as in `physac` or `rlgl` modules. I don't program C++ so I don't know if that is what we need and whether we should edit `physac`, `rlgl` and any other modules instead. But I parse these files to generate Nim language bindings so I'd like them to be as close as possible.
https://github.com/raysan5/raylib/blob/master/src/rlgl.h#L630
https://github.com/raysan5/raylib/blob/master/src/physac.h#L233

Move cplusplus curly brace and RAYGUI_H endifs above implementation

---

README.md

Related commit: https://github.com/raysan5/raygui/commit/b8932dab261bff56a407136cdd2432a03bd74090

Fix broken 'riconsdata' link in README.md

---

src/raygui.h

This pull request resolves the declaration conflict errors of  `GetCodepoint()` and `CodepointToUTF8()` [which are already implemented in raylib](https://github.com/raysan5/raylib/blob/master/src/raylib.h#L1338).
```
In file included from amber/src/editor.c:21:
amber/src/external/raygui.h:1256:12: error: static declaration of ‘GetCodepoint’ follows non-static declaration
1256 | static int GetCodepoint(const char *text, int *bytesProcessed); // Get next codepoint in a UTF-8 encoded text
|            ^~~~~~~~~~~~
In file included from amber/include/amber.h:23,
from amber/src/editor.c:18:
amber/lib/raylib/raylib.h:1338:11: note: previous declaration of ‘GetCodepoint’ was here
1338 | RLAPI int GetCodepoint(const char *text, int *bytesProcessed);        // Get next codepoint in a UTF-8 encoded …
```

Move declarations of GetCodepoint() and CodepointToUTF8()

---

README.md
examples/custom_file_dialog/custom_file_dialog.c
examples/portable_window/portable_window.c
examples/property_list/dm_property_list.h
examples/property_list/property_list.c
examples/text_editor/text_editor.c
src/gui_textbox_extended.h

Fixed some of the examples using `font.chars` to be `font.glyphs`, also changed `RAYGUI_SUPPORT_ICONS` to `RAYGUI_SUPPORT_RICONS` to fix icons (and made the readme reflect this as well).
Added `DrawTextRecEx` to gui_textbox_extended.h fix compilation errors due to it being removed from raylib, also fixed `font.chars` to be `font.glyphs`.

Fix some examples, fix part of gui_textbox_extended.h

---

src/raygui.h

Fixed bounds check so that out of bounds values don't persist until the next call to `GuiValueBox()`.
#164 is fixed by this PR.

Fixed bounds check in `GuiValueBox()`

---

src/raygui.h

The bounds check occurred before the `GuiButton`s for the increment and decrement feature of the `Spinner` control which meant using the buttons when the spinner value was at the `minValue` or `maxValue` and incremented or decremented past the min or max would not be resolved until the next time the `Spinner` control was called in the code, likely on the next iteration of a program loop. This caused an array index out of bounds issue in my codebase.
#163 is fixed by this PR.

Fixed Spinner control bounds check error

---

src/raygui.h

I am encountering following issue when building raygui on Raspbery PI zero (natively or cross-compiling).
Here's a fix.
I did not have the chance to test it on another architecture.

Fixed: incompatible type for argument 1 of 'UnloadTexture'

---

examples/Makefile

Updating frameworks for macOS to match latest raylib examples Makefile https://github.com/raysan5/raylib/blob/a940f41b4bfb681c9cbed9e95d1b73fee64d5bb8/examples/Makefile#L357
Related https://github.com/raysan5/raylib/pull/1022

Fix examples build for macOS

---

examples/controls_test_suite/controls_test_suite.c
examples/scroll_panel/gui_scroll_panel.c
src/raygui.h

GuiScrollPanel was changed to take a text parameter, but the examples weren't updated. These two failed to build without the change.

add text parameter to GuiScrollPanel examples

---

examples/custom_file_dialog/gui_file_dialog.h

In the Custom File Dialog example, currently it's hard to use it to create a new file when saving, since if you type a non-existing file in the text area, it will get deleted when you press the "Select" button. 
I have added a `saveFileMode` on the dialog's state so that, when this variable is true, the `fileNameText` won't get cleared for non-existing files. 
Since this is only an example, not sure if this PR is a good fit here.
Thanks!

Added 'saveFileMode' option to file dialog state

---

src/raygui.h

fixes #181 
Currently, when compiling under C++ using GCC 11, the following warning is generated
```
raygui.h: In function ‘int GuiTextInputBox(Rectangle, const char*, const char*, const char*, char*, int, int*)’:
raygui.h:3150:55: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
3150 |             ((*secretViewActive == 1) || textEditMode)? text : "****************", textMaxSize, textEditMode)) textEditMode = !textEditMode;
|             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
|                                                       |
|                                                       const char*
```
it looks like GCC promotes this to an error by default. It compiles fine if I pass -fpermissive.
I believe the cause of this issue is …

Fix GCC warning (by default an error) when using raygui from C++

---

README.md

This provides mac build instructions. Tested on OSX 12.3, on M1 hardware, with homebrew 3.4.2

Mac dynlib build instructions

---

src/raygui.h

Progressbar cannot visualy overflow anymore and returning value has meaning now. I considered adding min, but have not needed it yet.

Add max to GuiProgressBar

---

src/raygui.h

Fix for the issue #203, making sure a style is loaded by pulling a `GuiGetStyle` call out of the `MeasureTextEx` argument list.

Fix for unsafe call of MeasureTextEx in GetTextWidth #203

---

src/raygui.h

Currently when inserting a multibyte character to a `GuiTextBox` that almost reached its `textSize` limit, the end of that buffer could be overwritten, as the code expected every char to be just one byte.
The BACKSPACE handling also would just remove a single byte of a potential multibyte code point leaving invalid utf8.

GuiTextBox: Ensure utf8 dosn't overflow buffer and backspace handles it correctly

---

examples/controls_test_suite/controls_test_suite.c
src/raygui.h

This change handles `GuiIconText` calls with only an icon on a different buffer to allow the use in `GuiSpinner` and `GuiTextInputBox` to display the icons without overwriting user text given to these widgets. It was the least intrusive way I could think of to fix the issue. It would still be a problem if one uses `GuiSpinner` or `GuiTextInputBox` with only an icon as text, but that would look not great as a user experience anyways I guess.
This change would fix #205 and fix #206 and together with the small change in the `controls_test_suite.c` to match some previous change in raygui, it makes the `controls_test_suite.c` work again.

add distinct icon-only buffer for internal use

---

src/raygui.h

This change allows edits in GuiTextBox where the text is still fitting textSize but not the visual bounds. In the previous code this lead to an uneditable text box (example is rGuiStyler with style set to cyber disabling the hex color box).
It works by displaying the text right aligned and character clipped when in edit mode and text is overflowing.
As soon as the edit mode is left, the widget behaves as it did before, without clipping or adapted alignment.

GuiTextBox(): allow edits that fit textSize but not visual bounds

---

src/raygui.h

This change will fix `GuiTextBoxMulti` to handle inserting multibyte characters at the edge of textSize and backspace of bad multibyte sequences at the beginning of the buffer without out-of-bounds writes.

GuiTextBoxMulti(): Remove two potential out of bounds crashes

---

src/raygui.h

Make some strings const that are never modified.
Round and don't truncate by casting (comment says it wants to round). 
These fixes help raygui work better when compiled with C++ code.
Errors usually are
```
src/raygui.h: In function ‘void GuiDrawText(const char*, Rectangle, int, Color)’:
src/raygui.h:3940:43: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
3940 |         const char **lines = GetTextLines(text, &lineCount);
|                                           ^~~~
|                                           |
|                                           const char*
src/raygui.h:3892:27: note:   initializing argument 1 of ‘char** GetTextLines(char*, int*)’
3892 | char **GetTextLines(char *text, int *count)
|                     ~~~~~~^~~~
src/raygui.h:3940:42: …
```

Minor Fixes: Warning and errors when building for strict compilers

---

src/raygui.h

Instead of double casting a value to get it to truncate, this PR uses `floorf `to get the smallest whole number for the cell. This improves readability and would work for negative cells if that ever becomes a thing.

Minor : readability improvement in GuiCell

---

examples/custom_file_dialog/gui_file_dialog.h

This change fixes a type warning in gui_file_dialog.h...
```
examples/custom_file_dialog/gui_file_dialog.h: In function ‘GuiFileDialog’:
examples/custom_file_dialog/gui_file_dialog.h:313:198: warning: passing argument 2 of ‘GuiListViewEx’ from incompatible pointer type [-Wincompatible-pointer-types]
313 | dowBounds.y + 48 + 20, state->windowBounds.width - 16, state->windowBounds.height - 60 - 16 - 68 }, dirFilesIcon, state->dirFiles.count, &state->itemFocused, &state->filesListScrollIndex, state->filesListActive);
|                                                                                                     ^~~~~~~~~~~~
|                                                                                                     |
| …
```

gui_file_dialog: Fix warning

---

examples/Makefile
examples/custom_sliders/custom_sliders.c

These gui elements provide examples on how to extend the library.
They can be dropped as-is into a project, and the "owning" variants of the sliders solve #255 without changing the library API.

Added a new examples : vertical sliders and mouse-owning sliders

---

src/raygui.h

This PR allows users to control the BORDER_WIDTH of the text boxes (GuiTextBox and GuiTextBoxMulti) via GuiSetStyle.
Currently, the BORDER_WIDTH of the text boxes is taken into account when in the  'focused' or 'pressed' state. In the 'normal' state this is hard coded to 1. This change replaces the hard coded value and instead does a GuiGetStyle lookup.
By being able to control the TextBox's border we can achieve effects like -
However currently with the value hard coded to 1 you get this -
If this change is counter to Raygui's design or intent please feel free to close.
Thanks for your time.

Have GuiTextBox/GuiTextBoxMulti respect BORDER_WIDTH

---

projects/CMake/CMakeLists.txt
projects/CMake/cmake/FindRaylib.cmake

This updates the cmake definition files to target raylib 4.5. Also updates the examples list to build the new examples.

[cmake] Update to raylib 4.5

---

src/raygui.h

This makes creating a Rectangle use the RAYGUI_CLITERAL to fix some broken Windows builds.

Fix Rectangle instanitation with RAYGUI_CLITERAL

---

src/raygui.h

When ```RAYGUI_NO_ICONS``` defined, getting errors in ```GuiTabBar```. It seems this is copied from ```GuiWindowBox``` and then not edited and forgotten.

Fix error in GuiTabBar

---

src/raygui.h

Proposing to change type of ```textBoxCursorIndex``` from ```unsigned int``` to ```int``` for avoiding bunch of compiler warnings about signedness.
```textBoxCursorIndex``` is used in many arithmethic operations and comparions with int types, the only way to eliminate warnings, is either casting it to int everytime or declaring as int at the beginning. The latter is proposed.

Avoid compiler warning about signedness

---

src/raygui.h

Proposed change avoids hardcoded values and creates white rectangle exaclty like in ```rcore```

Avoid using hardcoded values in whitechar

---

src/raygui.h

Adding semi colon to fix #274 so RAYGUI_DEBUG_TEXT_BOUNDS can be used.

Fix #274 - Adding semicolon

---

src/raygui.h

This fixes the same problem mentioned in #33, but I guess this particular line was introduced later.
I see there's `RAYGUI_CLITERAL` but also `CLITERAL` from raylib, is there a reason for this distinction?

Fixed C++ compilation in C literal in call to SetShapesTexture

---

examples/custom_sliders/custom_sliders.c

`GuiSlider()` takes a `float *`, so we must retrieve the address of `value`, rather than just passing it in.

Fix GuiSlider value pointer

---

src/raygui.h

change clicked to result in the RAYGUI_NO_ICONS case.
```c
#if defined(RAYGUI_NO_ICONS)
result = GuiButton(closeButtonRec, "x");
#else
result = GuiButton(closeButtonRec, GuiIconText(ICON_CROSS_SMALL, NULL));
#endif
```
Cast (void*) to (unsigned char*), and fix pedantic C++ errors.
```c
unsigned char *... = (unsigned char *)RAYGUI_MALLOC(...);
```

Fix window result and pedantic error

---

src/raygui.h

Arrows are excluded to avoid dragging the scrollbar to the beginning/end when using them
Previous behavior:
https://github.com/raysan5/raygui/assets/24270152/85433f19-d2b4-4897-9ab0-03cff84b7f06
Fixed behavior:
https://github.com/raysan5/raygui/assets/24270152/41ee75a1-b559-463f-8363-a140cb64afdf

Fix GuiScrollBar dragging taking slider behavior

---

src/raygui.h

Add missing `RAYGUI_CLITERAL` and explicit float casts to `GuiDrawRectangle` call

Fix C++ build errors

---

src/raygui.h

Solves #315 by adding 2 to ```textWidth```.
All other controls that includes text have 2 pixel extra when measuring text width but somehow it's omitted in ```GuiMessageBox```.

Solve the issue with last letter of GuiMessageBox

---

src/raygui.h

textOffsetY is an int, but this addition had a float cast. This was causing issues when using raygui with implementation in zig.

minor fix, removed unnecessary float cast for textOffsetY

---

src/raygui.h

A pass to fix warnings in raygui.
One big signed/unsigned thing, and a switch without any cases.
For the unsigned signed issue, I made the global be signed because it's compared signed values.
For the switch, I added in some cases from a comment that just fall through and moved the comment into the case, so at least it'll be easy to add special handling for those cases if/when the time comes, and it gets rid of the warning.

Fix warnings in MSVC

---

src/raygui.h

This PR proposes a use to the "unused" `int result` seen in `GuiSliderPro()`. `result` will return 1 if the controlled value has been changed, 0 otherwise. 
From what raysan told me in the raylib discord, the results were added in the redesign to return the control's internal states, but they weren't properly designed as those can vary between controls.
I might explore some possible use cases of these return values for other controls later.

`GuiSliderPro()` returns 1/true if control value has changed

---

examples/animation_curve/gui_curve_editor.h

Hello, while testing your examples, I realized on example: "animation_curve" that you were using the function **`DrawLineBezierCubic`** which was deprecated on raylib5.0
As you explained, the ideal function to use would be **`DrawSplineSegmentBezierCubic`**
I've implemented this function and tested the program to make sure everything is working normally
Tested with : Linux Fedora 37 x86_64 GNU/Linux
I hope you find this useful and let me know if there is something else I should consider for this Pull Request.
Solves #348

Implemented new function DrawSplineSegmentBezierCubic to fix example

---

src/raygui.h

This addresses two issues I found with the slider.
1. When clicking once in a location, the offset of the slider is not centered.
2. When dragging the slider to the edges, the slider is not compensating for its width.
I also removed an extra branch, did the calculations for the slider value after we calculate everything, and removed the weird (additional) setting of the slider values (:2999-:3000)
Both seen here:
And the fixed version:
This needs tested with styles that have borders/padding.

Slider now centers correctly and general UX improvements

---

src/raygui.h

This fixes an issue where text can be drawn out of bounds if it is wider than the bounds or when an icon is used. Also, if text is center or right aligned, it can be positioned too far left, which is fixed by limiting the x position of the text to the left edge of the bounds.
Before:
After:
(Since the text is wider than the bounds, alignment has no effect)
Alignment still behaves normally if the text is not too long:

Fix `GuiDrawText()` sometimes drawing out of bounds

---

src/raygui.h

As discussed in #366, I transferred the dragging out of bounds behavior to `GuiColorPanelHSV()` and called it inside `GuiColorPanel()`, which simplifies code quite a lot.
I **did not** modify the return values of any functions and instead used a workaround where I compare the HSV values before and after the call to `GuiColrPanelHSV()`. Thus the API is not changed.
Tested on Linux:
- `GuiColorPanel[HSV]()`
- `GuiColorPicker()`
As best as I can tell, everything behaves the same, with the addition of the new dragging out of bounds behavior.

Commonise GuiColorPanelHSV and GuiColorPanel logic and behavior

---

examples/Makefile

The previous command did not work for me (the filters came out empty after grep) and seemed overly complex.

fixed and simplified make clean for examples on Linux

---

.gitignore

Since executables on Linux (and I believe OSX) don't have a .postfix they were not covered by the other ignores.
Note that I use the * wildcard which does not match arbitrary paths.

gitignore: ignore compiled examples for Linux and OSX

---

examples/floating_window/floating_window.c

A reusable floating window function. Window can be moved around through its title bar, minimized with its close button, resized from the icon in the lower right. The window is kept within the application area if the user pushes it outside the window/screen. The contents of the window are clipped with `BeginScissorMode` only if required and also a `GuiScrollPanel` enables user to see the clipped content of the window if current window size does not encapsulate all the content.

add floating window example

---

examples/Makefile
examples/floating_window/floating_window.c

Added floating_window example to the Makefile, fixed raygui path, and made the resizing a bit better.
https://github.com/raysan5/raygui/assets/122418017/8af7c210-10ec-45dd-8ebc-0853fbaff802
https://github.com/raysan5/raygui/assets/122418017/55de07ec-3f32-4e8f-9b62-d50722eddcff

fix floating window example

---

src/raygui.h

Documentation in raygui.h mentions method `GuiLoadStyleDefaulf` which likely should have been `GuiLoadStyleDefault`.

fix typo in raygui.h

---

src/raygui.h

When trying to use the floating window example, I got several times some crashes when expanding the window size.  It's caused in the GuiScrollBar function, when the maxValue is equal to the minValue (I don't know if this case is intended in the first place). Because valueRange variable is maxValue minus minValue, then it is equal to 0, and triggers a crash later, when we use it in division (division by 0).
I'm not sure if it's the best fix, maybe minValue == maxValue is not indentend in the first place and we should fix this problem earlier?

Fix division by zero in GuiScrollBar function

---

src/raygui.h

This fixes some issues, especially when using `GuiIconText` with `GuiGroupBox`. Thank you!

Fix icon padding adjustment in `GetTextWidth`

---

src/raygui.h

Fix a buffer overrun from using the global variable textBoxCursorIndex in GuiTextBox().
To reproduce overrun, have two GuiTextBox()es with different buffer sizes, and then the cursor index is shared between them, reading beyond the end of the array of the smaller buffer.
(Found because I run my debug builds with -fsanitize=address and this crashed my program :p )

GuiTextBox(): Fix buffer overrun from cursor index

---

src/raygui.h

Prevents going out of bounds before the beginning of the string

GuiTextBox(): Do not get previous code point when at start of string

---

src/raygui.h

The lack of cursor movement and shortcut support is a bit lacking, if you have any requirements for me to add other ctrl support I would be happy to do so!

add ctrl backspace support for deleting words

---

src/raygui.h

**Changes**:
Added GuiLoadIconsFromMemory
**Driver for change**:
I implemented this in order to unpack icons generated using rguiicons using rres cleanly like so:
```cpp
int idIcons = rresGetResourceId(dir, "icons.rgi");
rresResourceChunk chunkIcons = rresLoadResourceChunk("resources.rres", idIcons);
if(UnpackResourceChunk(&chunkIcons) == RRES_SUCCESS) {
GuiLoadIconsFromMemory((const unsigned char*) chunkIcons.data.raw, chunkIcons.info.baseSize, "iconsName");
}
rresUnloadResourceChunk(chunkIcons);
```
Follows the convention and usage of GuiLoadStyleFromMemory as closely as possible.

Add GuiLoadIconsFromMemory

---

src/raygui.h

**Changes:**
Use `snprintf` instead of `sprintf`. 
**Results:**
Works the same.  Avoid deprecation warnings during building, i. e.
```
warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
4193 |         sprintf(buffer, "#%03i#", iconId);
|         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/usr/include/_stdio.h:274:1: note: 'sprintf' has been explicitly marked deprecated here
274 | __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended …
```

fix: deprecation warning: sprintf -> snprintf

---

src/raygui.h

The knob rectangle of the the `GuiSliderPro` is not being drawn in disabled state, producing an empty slider. But it makes sense to see the current value of the slider even when it's disabled. So, this PR adds it.

Added drawing of Slider knob in disabled state

---

src/raygui.h

- Make the check match the defined macro

Fix mismatch between `if defined` and `define` for `RAYGUI_LINE_MARGIN_TEXT`.

---

src/raygui.h

- Un-hardcodes 18 and 20
- https://github.com/raysan5/raygui/issues/436
- https://github.com/drasmart/NumGuess-raygui/blob/8eacbcd0ef2c245034b45a69262b260006602102/src/main.cpp

Expose `RAYGUI_WINDOWBOX_CLOSEBUTTON_HEIGHT` in `GuiWindowBox`.

---

src/raygui.h

Handling paste similarly to how standard input boxes on Windows behave:
- will try to insert as much of the clipboard text as possible at the given cursor position, without overflowing the buffer
- will only add full codepoints
- will stop at any control character in the input (e.g. will only insert until a newline character in encountered, unless multiline is true - to prepare for future multiline support)
Assumes GetClipboardText() always returns either NULL or an UTF-8 encoded string (which sadly is not clearly documented, but seems to be true for at least the GLFW and SDL backends).
Tested with various extended latin characters and emojis, which all work as expected.

GuiTextBox paste support

---

src/raygui.h

The codeblocks handling the DELETE and BACKSPACE keys used the wrong codepointSize variable (the one for the key being pressed, instead of the codepoint being deleted).
Clicking with mouse iterated through the array without respect to the codepoint size.
This PR fixes both.

Fix GuiTextBox handling of codepoints when deleting text and clicking with mouse

---

src/raygui.h

Here is the change that caused this:
https://github.com/raysan5/raygui/commit/46fd886f18c6bed1017f1cd6e9db873b2816a828#diff-d01adeecbcae2a1e13b6832e327d5f84b9ec0e13aff89630006e99a24a9f2273L4304
I believe this change was accidental. 
At least I could not find an instance where the VALUEBOX, SLIDER_WIDTH style was accessed.

Fix GuiSlider not drawing handle

---

src/raygui.h

I've tried to implement the fix according to how I think it is meant to work, so I hope my preception is accurate.
For example:
The border around the filled bar is increased with the padding amount so it can reach its max value at the same time as the progress bar as it is squshed together from all direction now.
**Issue I tried to fix** 
- The rectangles on the right side of the GuiProgressBar() becomes weirdly offset by adding BOREDER_WIDTH
- The Fill bar gets padded incorrectly.
**Potential problems** 
- Setting padding or boarder width higher than the size of the GuiProgressBar() it behaves incorrecly. Protecting against this just hides the user error imo
- I have not tested that the boarder rectangles are not overlapping and I had a feeling from watching the previous code that they …

fixed border and padding offset issue caused by BORDER_WIDTH

---

src/raygui.h

Sooo, this PR became a bit bigger than I initially planned. Sorry about that.
I tried to keep the individual changes each in their own commit, so if the sum of changes is a bit too much to review, maybe you can go commit by commit.
Let me know, if I should do multiple PRs for something like this in the future.
Anyway, this does the following:
- Implement the correct bounds checking by @SirNate0
- Fix multiple problems related to CTRL+BACKSPACE handling. The behaviour should now mostly match nodepad, Notepad++ or other Windows applications with "standard" text processing (the one exception being holding CTRL+BACKSPACE)
- Implement that behaviour also for CTRL+DELETE, CTRL+LEFT and CTRL+RIGHT
- Simplify handling of "auto cursor" (reduce code a bit) and bring that behaviour also more in-line …

GuiTextBox() rework

---

src/raygui.h

```cpp
warning: enumerated mismatch in conditional expression: ‘GuiControlProperty’ vs ‘GuiDefaultProperty’ [-Wenum-compare]
1722 |                      GetColor(GuiGetStyle(DEFAULT, (state == STATE_DISABLED)? BASE_COLOR_DISABLED : BACKGROUND_COLOR)));
|                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Fix enum compare warning in GuiPanel

---

src/raygui.h

As requested by @raysan5 I removed the left-right padding I wrongfully added in my last pull request
Thanks for reaching out so I could fix the issue : )

removed left-right padding from GuiProgressBar

---

src/raygui.h

It was impossible to enter negative number.
Now pressing KEY_MINUS toggles sign for the value when value is not 0. Due to original implementation it's not possible to start entry with minus symbol or have added minus while the value is 0.

Add minus toggle for GuiValueBox & GuiValueBoxFloat

---

examples/custom_file_dialog/gui_window_file_dialog.h

Compiling the `custom_file_dialog` with `-Wall -Wextra` generates this warning

`custom_file_dialog`: `-Wsign-compare` warning

---

examples/controls_test_suite/controls_test_suite.c

Fixes: #511
Locking the GUI prevents other controls from stealing input from the GuiTextInputBox().
It also just makes sense to lock them, since they are greyed out.

Fix(examples/controls_test_suite): Lock other GUI elements when dialog window is open.
