src/raygui.h
Yesterday i sent you a message on Discord about this. I'll try to modify the other controls that need a scrollbar to use this.
=> Added GuiScrollBar()

src/raygui.h
Improved the widget with the following:
- rewrote the widget to use `GuiScrollBar()`
- added a horizontal scrollbar to scroll on the X axis
- added style option to draw the vertical scrollbar to the left or to the right (should be used by all widgets that have a vertical scrollbar but for now its only used by this)
- ability to move the scrollbars with the UP / DOWN / LEFT / RIGHT keys
PS: I think i messed up the code formatting again :(  Sorry!!!
**Preview**
**Quick example to test**
```c
const int screenWidth = 400;
const int screenHeight = 450;
Vector2 panelScroll = {99, -20};
void DrawGui() 
{
Rectangle panelRec = {20,40,200,150};
Rectangle panelContentRec = {0,0,340,340};
Rectangle view = {0,0,0,0};
panelScroll = GuiScrollPanel(panelRec, panelContentRec, panelScroll, &view); …
```
=> Improved GuiScrollPanel()

examples/gui_scroll_panel.c, src/raygui.h
Also fixed a bug with the slider going outside of the scrollbar in `GuiScrollBar()`. Here's a preview of the updated example.
=> Updated the scroll panel example

src/raygui.h
This is the last widget that has a scrollbar. To be honest i'm not satisfied with how i hacked the scrollbar into this thing, at some point someone (me?!) will have to rewrite it, probably to add `BeginScissorMode()` / `EndScissorMode()` for smooth scrolling. 
For now it works and i'm eager to start work on the text widgets so i'll leave it like that.
=> Added GuiScrollBar() to GuiListViewEx()

src/raygui.h
New `GuiTextBox()` implemented with unicode support, still a **WIP** needs **more testing** and the code lots of polish and cleanup to be any good, but the **core is there** and all shortcuts work far better than the previous version.
`GuiSpinner()` and `GuiValueBox()` both depend on it now and while i was at it also fixed some problems with min/max values in `GuiSpinner()` and made the buttons change the value when held down...but still not fine tuned yet (since there can only be one textbox active i can get rid of framesCounter and replace it with a variable that stores `GetTime()` and that will work better for selecting/movement...)
Finally there are some function for programmatically controlling the textboxes, these should work but need to test them more and not just on textboxes but …
=> WIP modified GuiTextBox(), GuiSpinner() and GuiValueBox()

src/raygui.h
Allows you to set the hue you want to display in a GuiColorPanel even if the color you pass in is grey.
=> Color panel hue

src/raygui.h
Type of `GuiTextBoxGetState()` and the argument of `GuiTextBoxSetState()` is `GuiTextBoxState`, not `int`.
=> GuiTextBoxGetState() and GuiTextBoxSetState() types fixed

LICENSE, examples/controls_test_suite/controls_test_suite.c, examples/image_exporter/image_exporter.c, examples/image_raw_importer/image_raw_importer.c, examples/portable_window/portable_window.c, src/raygui.h
Also adds missing license information to `image_exporter.c`
=> Update year of copyright notices and fix typo

src/raygui.h
GuiSpinner and ValueBox were being disabled when the  RAYGUI_TEXTBOX_EXTENDED was set.
This PR moves GuiSpinner and GuiValueBox outside of the else statement for RAYGUI_TEXTBOX_EXTENDED and moves the GuiTextBox into it.
=> Fixed GuiSpinner defines

examples/image_raw_importer/image_raw_importer.c, examples/scroll_panel/gui_scroll_panel.c
So is SLIDER_SIZE supposed to be SLIDER_WIDTH?
=> Fix parameters and guess at constants

examples/property_list/dm_property_list.h, examples/property_list/property_list.c
Hey @raysan5! Made this thing some time ago and just updated it today to run with current raygui, think it might be useful but i might be wrong so it's ok if you don't merge!
Have a nice day!
=> Added new example for a custom property list control!

cmake/FindRaylib.cmake
Fixed package mode to prevent infinite recursion.
=> fixed package mode in FindRaylib

src/raygui.h
Rectangle in raygui should use a float.
=> Update raygui Rectangle to match raylib Rectangle

projects/CMake/CMakeLists.txt, projects/CMake/cmake/FindRaylib.cmake
Fixes #89 by only trying to load raylib if you're building the examples.
=> Update CMake definition files

README.md
=> Change "handcrafter" to "handcrafted" in README

src/raygui.h
Just add horizontal scroll (on `Shift`+`Mouse wheel`) for Scroll Panel control 😀
=> Add horizontal scroll

src/raygui.h
=> Move include guard endif to end of file

src/raygui.h
I added the dependency on the BORDER_WIDTH style to:
- ColorPicker
- HueSelector
- AlphaSelector
- GuiComboBox
all of them were hardcoded to 1 before
=> fix missing borderwidth

src/raygui.h
Added the new text parameter to the signature for the implementation of GuiScrollPanel. 
Fixes #173
=> Fixed implementation signature of GuiScrollPanel

examples/controls_test_suite/controls_test_suite.c, examples/property_list/dm_property_list.h, examples/property_list/property_list.c, examples/text_box_selection/textbox_extended_demo.c, src/extras/gui_textbox_extended.h
Some of the examples were not compiling. These changes bring it to the latest so that they compile again.
=> Update the examples to match the latest raygui.h

src/raygui.h
This PR fixes the first issue referenced in #200.
=> Fix lgtm warnings

src/raygui.h
PR #211 introduced an error from the PR preparation, this fixes it.
=> Fix merge bug introduced with #211

examples/custom_file_dialog/gui_file_dialog.h, examples/text_editor/text_editor.c, projects/CMake/cmake/FindRaylib.cmake
This updates to raylib 4.2. There's still something wrong with `custom_file_dialog` though.
=> Update to raylib 4.2

src/raygui.h
Added Image struct def, updated Font struct to match raylib.
Image is required for RAYGUI_STANDALONE flag to work Font was out of sync with raylib master
=> Added Image definition for RAYGUI_STANDALONE

examples/Makefile, examples/animation_curve/animation_curve.c, examples/animation_curve/gui_curve_edit.h
This is a demo to showcase raygui in a simple animation tool. It also shows that the raygui style system is easy to integrate for custom controls.
Demo in action here:
https://www.reddit.com/r/raylib/comments/12ezor0/animation_curves_demo_in_c/
=> Added a new example: animation curves

examples/animation_curve/gui_curve_edit.h
Old comment, _EvalGuiCurve_ doesn't return normalized y anymore.
=> missleading doc in gui_curve_edit

src/raygui.h
=> Fix for #278

src/raygui.h
Fixes incorrect comment from issue #277
=> Fix for #277

src/raygui.h
Adds support for HOME, END, and DELETE keys to GuiTextBox.
=> GuiTextBox improvements

src/raygui.h
A fix for sliders not dragging outside of bounds.
Added 2 global variables: a state for slider dragging and a rectangle as an identifier for the slider. This way it's possible to fix sliders without breaking changes.
=> Fix for sliders

examples/animation_curve/gui_curve_edit.h
In C, the struct is not allowed to have default values, as used in examples/animation_curve/gui_curve_edit.h . This PR fixes that and one minor line of code.
=> Fixed few stuff about animation curve example

src/raygui.h
This is an alternative implementation of the color picker control.
This implementation receives color value as HSV. It thus does not have to convert the received color value from RGB to HSV and the value picked by the user from HSV to RGB. The conversions are supposed to happen on the user side.
Because of this it avoids hue jittering when the user drags the selector in the color panel.
Here's an example of use and comparison with existing GuiColorPicker(): 
[https://gist.github.com/Durobot/810eacba2669e04c4afd79cb0db8b354](https://gist.github.com/Durobot/810eacba2669e04c4afd79cb0db8b354)
To see the difference, pick a hue between green and blue, or between red and yellow and drag the selector box in the color panel.
=> Added GuiColorPickerHSV() and GuiColorPanelHSV()

src/raygui.h
=> Fix progressbar border (#303)

examples/Makefile, examples/custom_input_box/custom_input_box.c
Turned my previous pull request into an example, as you suggested.
=> Added example of a calculator app with custom input box

examples/custom_file_dialog/custom_file_dialog.c, examples/custom_file_dialog/gui_window_file_dialog.h
Addresses #312 and adds OS specific path seperator char.
=> OS Specific path seperator char

examples/controls_test_suite/controls_test_suite.c, src/raygui.h
=> Add Toggle Slider (#305)

src/raygui.h
Hello! This pr fixes an issue with `GuiColorPanel()` where, unlike sliders, the element would not properly track a drag once the mouse exited the bounds. No new global variables are added.
**Before**
https://github.com/raysan5/raygui/assets/113054217/a2830c29-9354-4491-926d-0d214eee17de
**After**
https://github.com/raysan5/raygui/assets/113054217/c43d9b88-3801-477a-9540-f7a4a90a8ef7
Thank you very much!
=> Fixed dragging GuiColorPanel outside of bounds.

src/raygui.h
I added some Notes, to hopefully point people in the right direction when facing issue #369
=> added documentation on Hue control issues with GuiColorPicker

src/raygui.h
Test on `scroll_panel.c` example using 100 for bounds width and height.
https://github.com/raysan5/raygui/assets/46388933/7df42e13-e006-4e8e-9cd2-5a12ec985727
=> GuiScrollPanel dynamic mouse scroll speed

examples/custom_input_box/custom_input_box.c
and TextToFloat seems to be deprecated so removed it
=> fix compile error in custom input example

src/raygui.h
Wanted to add a little convenience to these functions to allow for the keypad enter key to be used for confirming.
=> Support keypad Enter key with GuiValueBox and GuiValueBoxFloat.

README.md
Added the move since it restores the state of the files to normal again. I considered copying, decided not to since copying adds an unnecessary file.
=> README: Added move in building for linux

examples/portable_window/portable_window.c
Fixes: https://github.com/raysan5/raygui/issues/468
=> [portable_window] fix window flicker when moving it without dragging the bar.

src/raygui.h
I was having issues using it in conjunction with raylib (in Windows), so added these annotations here.
Let me know if it's okay, thanks for the project, Ray!!
=> Export GuiSliderPro and add static to GetTextLines (for shared libs)

src/raygui.h
=> Fix integer overflow potential

examples/custom_input_box/custom_input_box.c, examples/custom_sliders/custom_sliders.c, examples/image_exporter/image_exporter.c, examples/image_importer_raw/image_importer_raw.c, examples/property_list/dm_property_list.h
The examples contained what I think are outdated usages of the API. I updated them so now they should compile properly.
=> Fixed examples
